"""add new models and extend company

Revision ID: 26bb8c9d58d5
Revises: d2152121e58b
Create Date: 2026-02-12 10:23:09.602357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '26bb8c9d58d5'
down_revision: Union[str, None] = 'd2152121e58b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('operator_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('analysis_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=True),
    sa.Column('stage_confidence', sa.Integer(), nullable=True),
    sa.Column('pain_signals_json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('evidence_bullets', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('raw_llm_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('briefing_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('why_now', sa.Text(), nullable=True),
    sa.Column('risk_summary', sa.Text(), nullable=True),
    sa.Column('suggested_angle', sa.Text(), nullable=True),
    sa.Column('outreach_subject', sa.String(length=255), nullable=True),
    sa.Column('outreach_message', sa.Text(), nullable=True),
    sa.Column('briefing_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('companies', sa.Column('founder_linkedin_url', sa.String(length=2048), nullable=True))
    op.add_column('companies', sa.Column('company_linkedin_url', sa.String(length=2048), nullable=True))
    op.add_column('companies', sa.Column('source', sa.String(length=32), server_default='manual', nullable=False))
    op.add_column('companies', sa.Column('target_profile_match', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('companies', sa.Column('current_stage', sa.String(length=64), nullable=True))
    op.add_column('signal_records', sa.Column('source_type', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signal_records', 'source_type')
    op.drop_column('companies', 'current_stage')
    op.drop_column('companies', 'target_profile_match')
    op.drop_column('companies', 'source')
    op.drop_column('companies', 'company_linkedin_url')
    op.drop_column('companies', 'founder_linkedin_url')
    op.drop_table('briefing_items')
    op.drop_table('analysis_records')
    op.drop_table('users')
    op.drop_table('operator_profiles')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
